default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: onlinecatering_development

test:
  <<: *default
  database: onlinecatering_test

production:
  <<: *default
  database: onlinecatering_production
  username: onlinecatering
  password: <%= ENV['ONLINECATERING_DATABASE_PASSWORD'] %>
